### ISSUE TITLE
Undocumented delay required after start()

### ISSUE THREAD

**Issue by songzh96** [klenae/python-cipclient#11]
Hi

This is a good plugin and I am trying to use him.

I added an xpanel2.0 smart graphics to simpl windows, and then I ran the code, but found no signal output in simpl debug.
The code did not report an error.

```
cip = cipclient.CIPSocketClient ("AV3-7F932FBD", 0x0B)

# initiate the socket connection and start worker threads
cip.start ()

# you can force this client and the processor to resync using an update request
cip.update_request () # note that this also occurs automatically on first connection

# for joins coming from this client going to the processor
cip.set ("d", 1, 1) # set digital join 1 high

```

**Comment by klenae** [comment]
If you add a delay of at least 1.5 seconds after `cip.start()` it should fix the issue for you.  I will probably build this delay in to the start() method in the next release, but in the meantime you can add `import time` and put a `time.sleep(1.5)` after `cip.start()`.

**Comment by klenae** [comment]
For now I have updated the example code in the README to include the required delay.  Thank you for reporting the issue!

**Comment by songzh96** [comment]
ok thank you
 I will try

by the way, If my PC IP is 192.168.20.33 and the professor IP is 192.168.10.160， I can Ping it.
Will this cause the connection to be unsuccessful?

**Comment by klenae** [comment]
Having your PC and control processor on different subnets should be fine, as long as your network is set up correctly.  If you are unsure, try running an executable or web XPanel on your PC - if that won't connect correctly to the control processor than this module won't be able to either.

**Comment by songzh96** [comment]
I tested it again today and still can't see the corresponding output signal in the toolbox.

Is it possible to write a detailed tutorial? Convenient for everyone to use your plugin.

Best Regards
songzh

**Comment by klenae** [comment]
I will be looking at the documentation / examples / logging / etc. at some point, and will include a 'getting started' tutorial.  At the moment I am still working on developing and testing the core functionality.  In the meantime, you can try the following code, which will press and release digital join 1 continuously until you press `CTRL-C`:

```python
import time
import logging
from cipclient import CIPSocketClient

logging.basicConfig(level=logging.DEBUG, format="[%(levelname)s] (%(threadName)-10s) %(message)s")

cip = CIPSocketClient("AV3-7F932FBD", 0x0B)
cip.start()

time.sleep(1.5)

try:
    while True:
        cip.press(1)
        time.sleep(2)
        cip.release(1)
        time.sleep(2)

except KeyboardInterrupt:
    cip.stop()
```

I have tested this on a windows PC and a Raspberry Pi, and it works fine on both.  Note that logging is enabled, so you should see lots of information if it works, and hopefully a hint about why it isn't working if it doesn't.  You can also enable the same logging in your own code by including the `import logging` and `logging.basicConfig` lines.

**Comment by songzh96** [comment]
Hi @klenae 

I failed again because the link failed.
This is my logs

```
[DEBUG] (MainThread) start requested
[DEBUG] (Connection) started
[DEBUG] (Connection) attempting to connect to CP3-7FBD928A:41794, no success yet
```

But I can use Xpanel to control it.

**Comment by klenae** [comment]
The debug output indicates that the socket connection is failing.  That could be for any number of reasons, although the fact that you can ping the processor and connect via XPanel (I am assuming from the same machine that you are testing this module from) is curious.  Can you verify the following:

* Python version used for testing?  (must be >= 3.6)
* Platform used for testing? (PC/Mac/Raspberry Pi/etc.)
* Operating system used for testing?
* Is authentication and/or SSL enabled on the Crestron processor?
* What firmware version is the processor running?

Other things you could try:
* Does it work if the firewall on the test machine is temporarily disabled?
* Does it work if the test machine is on the same subnet as the control processor?

**Comment by songzh96** [comment]
Thank you for your help, I just tested it failed again.
 I think it is my network problem. I will try slowly if I have time

1. 3.6.6
2. PC
3. WIN10
4. No

Other
1. Failed
2. Failed
